version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "1234:1234"
    environment:
      - REMIX_PORT=3000
      - YJS_PORT=1234
      - HOST=0.0.0.0
      - NODE_ENV=production
      - HOST_URL=${HOST_URL:-http://localhost:1234}
    volumes:
      - ./storage-location:/usr/src/app/storage-location